version: 2
jobs:
  build-base: &build-base
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/tmtk75/librarian-puppet-go
    steps:
      - checkout
      - run: go get -v github.com/golang/dep/cmd/dep
      - run: dep ensure
      - run: make build
      - run: go test -v .

  go1.8:
    <<: *build-base

  go1.7:
    <<: *build-base
    docker:
      - image: circleci/golang:1.7

workflows:
  version: 2
  build_and_test:
    jobs:
      - go1.8
      #- go1.7
